[build]
  publish = "public" # This tells Netlify where your static files are
  functions = "netlify/functions" # This tells Netlify where your functions are

# Optional: If you want to use a specific Node.js version for functions
[functions]
  node_bundler = "esbuild" # Or "zip"
  node_version = "18" # Or "20"