[build]
  publish = "public"
  command = "npm install && npm run build" # Assumes you have a build script, will create one if needed

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200